// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations.AdminLogDb
{
    [DbContext(typeof(AdminLogDbContext))]
    [Migration("20250408084018_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Log.RequestAdminLog", b =>
                {
                    b.Property<long>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RequestId"));

                    b.Property<DateTime>("CallTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Guid")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("MethodInput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MethodOrginalId")
                        .HasColumnType("int");

                    b.Property<long>("PointerId")
                        .HasColumnType("bigint");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceMethodId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceOrginalId")
                        .HasColumnType("int");

                    b.Property<string>("SummeryData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UrlCode")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.ToTable("RequestAdminLog");
                });

            modelBuilder.Entity("Domain.Entities.Log.ResponseAdminLog", b =>
                {
                    b.Property<long>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ResponseId"));

                    b.Property<DateTime>("CallTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ErrorCode")
                        .HasColumnType("int");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guid")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("MethodInput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MethodOrginalId")
                        .HasColumnType("int");

                    b.Property<string>("MethodOutput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PointerId")
                        .HasColumnType("bigint");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ResponseTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceMethodId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceOrginalId")
                        .HasColumnType("int");

                    b.Property<string>("SummeryData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UrlCode")
                        .HasColumnType("int");

                    b.HasKey("ResponseId");

                    b.ToTable("ResponseAdminLog");
                });
#pragma warning restore 612, 618
        }
    }
}
